### ISSUE TITLE
Spinnaker localhost run issue

### ISSUE THREAD

**Issue by kader81** [GoogleCloudPlatform/spinnaker-deploymentmanager#1]
I have followed the instructions as mentioned in the readme. Spinnaker instances are created. But in the last - there is a command to issue http://localhost:9000 - can you elaborate on this. 

I used gcloud shell from the console to execute the commands. I used web preview with port 9000, it always says could not connect to the machine. Can you pl. help on this.

**Comment by viglesiasce** [comment]
You need to run the gcloud compute ssh command from your local machine.
