### ISSUE TITLE
https/http Mixed Content Error from Spinnaker UI

### ISSUE THREAD

**Issue by urlbox-io** [GoogleCloudPlatform/spinnaker-deploymentmanager#9]
When trying to create a new application from the Spinnaker UI, getting the following error in the dev tools console in chrome:

vendor.bundle.js:31822 Mixed Content: The page at 'https://spinnakereruiaddressfromcloudshellpreview' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:8081/gate/applications'. This request has been blocked; the content must be served over HTTPS.

**Comment by danisla** [comment]
Fixed with #18
